### ISSUE TITLE
Connectivity problem cause unhandled exception that kills the host process

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus.SqlServer#1056]
When there is an issue with connection, the delayed delivery handling mechanism throws an exception that is not handled, bubbles up and kills the hosting process

```C#
FTL| NServiceBus.Transport.SqlServer.DueDelayedMessageProcessor | Exception thrown while moving matured delayed messages
System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 0 - No connection could be made because the target machine actively refused it.)
---> System.ComponentModel.Win32Exception (10061): No connection could be made because the target machine actively refused it.
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen()
--- End of stack trace from previous location ---
   at NServiceBus.Transport.SqlServer.SqlConnectionFactory.<>c__DisplayClass2_0.<<Default>b__0>d.MoveNext() in /_/src/NServiceBus.Transport.SqlServer/Configuration/SqlConnectionFactory.cs:line 46
--- End of stack trace from previous location ---
   at NServiceBus.Transport.SqlServer.SqlConnectionFactory.OpenNewConnection() in /_/src/NServiceBus.Transport.SqlServer/Configuration/SqlConnectionFactory.cs:line 26
   at NServiceBus.Transport.SqlServer.DueDelayedMessageProcessor.MoveMaturedDelayedMessages() in /_/src/NServiceBus.Transport.SqlServer/DelayedDelivery/DueDelayedMessageProcessor.cs:line 47
ClientConnectionId:00000000-0000-0000-0000-000000000000
```

**Comment by SzymonPobiega** [comment]
It seems that the issue has been created prematurely. After quick verification in code it is not possible that the process is killed because of this particular exception because it is property handled.
