### ISSUE TITLE
 Exception "Index was outside the bounds of the array" is thrown when using version 7.0.0 and Always Encrypted Columns

### ISSUE THREAD

**Issue by cquirosj** [Particular/NServiceBus.SqlServer#1150]
### Symptoms

After upgrading to version 7.0.0. when using a database with with always-encrypted columns the following exception is thrown when reading messages.

warn: NServiceBus.Transport.SqlServer.MessageReceiver[0]

The circuit breaker for message processing is now in the armed state
warn: NServiceBus.Transport.SqlServer.RepeatedFailuresOverTimeCircuitBreaker[0]
at NServiceBus.Transport.SqlServer.MessageReceiver.ProcessMessagesSwallowExceptionsAndReleaseConcurrencyLimiter(CancellationTokenSource stopBatchCancellationTokenSource, SemaphoreSlim localConcurrencyLimiter, CancellationToken messageProcessingCancellationToken) in /_/src/NServiceBus.Transport.SqlServer/Receiving/MessageReceiver.cs:line 210
at NServiceBus.Transport.SqlServer.ProcessWithTransactionScope.ProcessMessage(CancellationTokenSource stopBatchCancellationTokenSource, CancellationToken cancellationToken) in /_/src/NServiceBus.Transport.SqlServer/Receiving/ProcessWithTransactionScope.cs:line 29
at NServiceBus.Transport.SqlServer.TableBasedQueue.TryReceive(SqlConnection connection, SqlTransaction transaction, CancellationToken cancellationToken) in /_/src/NServiceBus.Transport.SqlServer/Queuing/TableBasedQueue.cs:line 54
at NServiceBus.Transport.SqlServer.TableBasedQueue.ReadMessage(SqlCommand command, CancellationToken cancellationToken) in /_/src/NServiceBus.Transport.SqlServer/Queuing/TableBasedQueue.cs:line 85
at NServiceBus.Transport.SqlServer.MessageRow.Read(SqlDataReader dataReader, Boolean isStreamSupported, CancellationToken cancellationToken) in /_/src/NServiceBus.Transport.SqlServer/Queuing/MessageRow.cs:line 22
at NServiceBus.Transport.SqlServer.MessageRow.ReadRow(SqlDataReader dataReader, Boolean isStreamSupported, CancellationToken cancellationToken) in /_/src/NServiceBus.Transport.SqlServer/Queuing/MessageRow.cs:line 48
at NServiceBus.Transport.SqlServer.MessageRow.GetNonStreamBody(SqlDataReader dataReader, Int32 bodyIndex, CancellationToken cancellationToken) in /_/src/NServiceBus.Transport.SqlServer/Queuing/MessageRow.cs:line 97
at Microsoft.Data.SqlClient.SqlDataReader.get_Item(Int32 i)
at Microsoft.Data.SqlClient.SqlDataReader.GetValue(Int32 i)
at Microsoft.Data.SqlClient.SqlDataReader.GetValueInternal(Int32 i)
at Microsoft.Data.SqlClient.SqlDataReader.CheckDataIsReady(Int32 columnIndex, Boolean allowPartiallyReadColumn, Boolean permitAsync, String methodName)
System.IndexOutOfRangeException: Index was outside the bounds of the array.
Message processing failed

### Who's affected

Users of version 7.0.0.

### Root cause
When using a connection string with `Column Encryption Setting = Enabled`, an incorrect column index is being used for accessing the message `Body` column value

**Comment by jpalac** [comment]
We've prioritized this issue near the top of our list and will work on it as soon as we can.
