### ISSUE TITLE
Unhandled Exception: System.ObjectDisposedException: Cannot access a disposed object.

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus.SqlServer#213]
When I try to send with to producers into the same Sql Azure Database the endpoints crash with the following exception:

```
Unhandled Exception: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'SqlDelegatedTransaction'.
   at System.Data.SqlClient.SqlDelegatedTransaction.GetValidConnection()
   at System.Data.SqlClient.SqlDelegatedTransaction.Rollback(SinglePhaseEnlistment enlistment)
   at System.Transactions.DurableEnlistmentAborting.EnterState(InternalEnlistment enlistment)
   at System.Transactions.DurableEnlistmentActive.InternalAborted(InternalEnlistment enlistment)
   at System.Transactions.TransactionStateAborted.EnterState(InternalTransaction tx)
   at System.Transactions.TransactionStateActive.Rollback(InternalTransaction tx, Exception e)
   at System.Transactions.EnlistableStates.Timeout(InternalTransaction tx)
   at System.Transactions.Bucket.TimeoutTransactions()
   at System.Transactions.BucketSet.TimeoutTransactions()
   at System.Transactions.TransactionTable.ThreadTimer(Object state)
   at System.Threading.TimerQueueTimer.CallCallbackInContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.TimerQueue.AppDomainTimerCallback()
```

I tried to wrap the sends with

```
using (var tx = new TransactionScope(TransactionScopeOption.Suppress, TransactionScopeAsyncFlowOption.Enabled))
            {}
```

It doesn't help

**Comment by tmasternak** [comment]
@danielmarbach can was trying to reproduce by failed. Can you share the code?

**Comment by danielmarbach** [comment]
I used https://github.com/danielmarbach/SwissChocolate.Power and tweaked it with Azure SQL database

**Comment by tmasternak** [comment]
@danielmarbach I've updated the sample to newest versions of Core [rc1] and SqlServer [beta7] and run it on Azure Sql several times but could not reproduce the issue.
