### ISSUE TITLE
Endpoint Queue Table Not Created - 3.0.0-beta0003

### ISSUE THREAD

**Issue by ppittle** [Particular/NServiceBus.SqlServer#280]
I'm using [NServiceBus SqlServer 3.0.0-beta0003](https://www.nuget.org/packages/NServiceBus.SqlServer/3.0.0-beta0003) to build a Test Harness where 
I start several endpoints.  Most of them start correctly and I can see message traffic.  However, one of them appears to start then starts throwing `SqlException (0x80131904): Invalid object name 'dbo.WhatTimeIsItJob-Q'` exceptions from `ExpiredMessagesPurger ` and most importantly when I send a message to that queue.

When I check my sql database after running the code, the table `WhatTimeIsItJob-Q` does not exist.

If I re-run the same code using [Azure Transports WindowsAzureStorageQueues 7.0.0-beta005](https://www.nuget.org/packages/NServiceBus.Azure.Transports.WindowsAzureStorageQueues/7.0.0-beta0005) I have no issue with queue creation and all of my queues are created fine.

_Is there some way to troubleshoot this?  Is there some limitation in SqlServer Transport?  Is there a bug where the table is delete/not created if `ExpiredMessagePurger` or `Index_Expires` fails?_

**Exceptions on Creation:**
```
2016-07-19 18:53:24,672 [20] INFO  SkyKick.Engine.Job.Runtime.JobBank.IJobEndpointManager - Starting Endpoint for Job [What Time Is It Job] at [WhatTimeIsItJob-Q]
2016-07-19 18:53:24,954 [15] WARN  NServiceBus.Transport.SQLServer.TableBasedQueue - Table [dbo].[WhatTimeIsItJob-Q] does not contain index 'Index_Expires'.
Adding this index will speed up the process of purging expired messages from the queue. Please consult the documentation for further information.
2016-07-19 18:53:24,959 [14] WARN  NServiceBus.Transport.SQLServer.ExpiredMessagesPurger - Purging expired messages from table [dbo].[WhatTimeIsItJob-Q] failed after purging 0 messages. Exception: System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'dbo.WhatTimeIsItJob-Q'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQueryAsync(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.SQLServer.TableBasedQueue.<PurgeBatchOfExpiredMessages>d__13.MoveNext() in C:\Build\src\NServiceBus.SqlServer\Queuing\TableBasedQueue.cs:line 147
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.SQLServer.ExpiredMessagesPurger.<Purge>d__7.MoveNext() in C:\Build\src\NServiceBus.SqlServer\Receiving\ExpiredMessagesPurger.cs:line 37
2016-07-19 18:53:24,959 [15] WARN  NServiceBus.Transport.SQLServer.RepeatedFailuresOverTimeCircuitBreaker - The circuit breaker for SqlPeek is now in the armed state
2016-07-19 18:53:24,965 [22] WARN  NServiceBus.Transport.SQLServer.TableBasedQueue - Table [dbo].[WhatTimeIsItJob-Q.1] does not contain index 'Index_Expires'.
Adding this index will speed up the process of purging expired messages from the queue. Please consult the documentation for further information.
2016-07-19 18:53:24,969 [15] WARN  NServiceBus.Transport.SQLServer.RepeatedFailuresOverTimeCircuitBreaker - The circuit breaker for SqlPeek is now in the armed state
2016-07-19 18:53:24,969 [4] WARN  NServiceBus.Transport.SQLServer.ExpiredMessagesPurger - Purging expired messages from table [dbo].[WhatTimeIsItJob-Q.1] failed after purging 0 messages. Exception: System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'dbo.WhatTimeIsItJob-Q.1'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQueryAsync(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.SQLServer.TableBasedQueue.<PurgeBatchOfExpiredMessages>d__13.MoveNext() in C:\Build\src\NServiceBus.SqlServer\Queuing\TableBasedQueue.cs:line 147
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.SQLServer.ExpiredMessagesPurger.<Purge>d__7.MoveNext() in C:\Build\src\NServiceBus.SqlServer\Receiving\ExpiredMessagesPurger.cs:line 37
```
**Exceptions on Sending a message:**
```
2016-07-19 18:53:31,644 [29] INFO  NServiceBus.FirstLevelRetriesBehavior - First Level Retry is going to retry message '7dd0d892-a3eb-4ed7-85f5-a64801374fc1' because of an exception:
NServiceBus.Unicast.Queuing.QueueNotFoundException: Failed to send message to [dbo].[WhatTimeIsItJob-Q] ---> System.Data.SqlClient.SqlException: Invalid object name 'dbo.WhatTimeIsItJob-Q'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader()
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQueryAsync(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.SQLServer.TableBasedQueue.<SendRawMessage>d__9.MoveNext() in C:\Build\src\NServiceBus.SqlServer\Queuing\TableBasedQueue.cs:line 91
   --- End of inner exception stack trace ---
   at NServiceBus.Transport.SQLServer.TableBasedQueue.ThrowQueueNotFoundException(SqlException ex) in C:\Build\src\NServiceBus.SqlServer\Queuing\TableBasedQueue.cs:line 119
   at NServiceBus.Transport.SQLServer.TableBasedQueue.<SendRawMessage>d__9.MoveNext() in C:\Build\src\NServiceBus.SqlServer\Queuing\TableBasedQueue.cs:line 101
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.SQLServer.TableBasedQueueDispatcher.<Send>d__6.MoveNext() in C:\Build\src\NServiceBus.SqlServer\Sending\TableBasedQueueDispatcher.cs:line 99
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.SQLServer.TableBasedQueueDispatcher.<DispatchUsingReceiveTransaction>d__5.MoveNext() in C:\Build\src\NServiceBus.SqlServer\Sending\TableBasedQueueDispatcher.cs:line 85
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.SQLServer.TableBasedQueueDispatcher.<DispatchAsNonIsolated>d__3.MoveNext() in C:\Build\src\NServiceBus.SqlServer\Sending\TableBasedQueueDispatcher.cs:line 49
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.SQLServer.MessageDispatcher.<Dispatch>d__1.MoveNext() in C:\Build\src\NServiceBus.SqlServer\Sending\MessageDispatcher.cs:line 22
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.TransportReceiveToPhysicalMessageProcessingConnector.<Invoke>d__1.MoveNext() in C:\Build\src\NServiceBus.Core\Pipeline\Incoming\TransportReceiveToPhysicalMessageProcessingConnector.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.FirstLevelRetriesBehavior.<Invoke>d__1.MoveNext() in C:\Build\src\NServiceBus.Core\Recoverability\FirstLevelRetries\FirstLevelRetriesBehavior.cs:line 21
```

**Comment by MarcinHoppe** [comment]
@ppittle Thanks for reporting this. Can you post the configuration code for the endpoint that causes this behavior?

**Comment by ppittle** [comment]
@MarcinHoppe - Hear's the code.  I use the same configuration for multiple endpoints and they all work fine, so not sure what's special about the one that's failing.  And not sure if this should matter, but I'm using SQL Express against a local db file as well:

```
public EndpointConfiguration Build(
            string queueName, string queueConnectionString, string persistenceConnectionString)
        {
           var config = new EndpointConfiguration(queueName);

            // This is necessary to support NServiceBus.Callbacks, hopefully
            // it should go away at NSB 6 RC.  But for now, I don't see any 
            // huge down sides, and Callbacks (I think will be) very handy for 
            // testing.
            //https://github.com/Particular/NServiceBus.Callbacks/issues/24
            config.ScaleOut().InstanceDiscriminator("1");

            config.UseSerialization<NewtonsoftSerializer>();
            config.EnableInstallers();
            config.SendFailedMessagesTo("error");
            
            config.UseTransport<SqlServerTransport>()
                .ConnectionString(queueConnectionString);
            config.UsePersistence<InMemoryPersistence>();

            config.License(
                GetType().Assembly.GetEmbeddedResourceAsString(
                    "SkyKick.Engine.Csr.Runtime.NServiceBusLicense.xml"));

            config.Pipeline.Register<LogIncomingMessageBehavior.Registration>();

            return config;
        }
```

**Comment by MarcinHoppe** [comment]
@ppittle What is the endpoint name (`queueName` argument) that you are passing for the endpoint that exhibits the failure? Does the starting the endpoint succeed?

**Comment by ppittle** [comment]
`queueName: "WhatTimeIsItJob-Q"`

Below is a screenshot of the database showing several other queues being created.

They all run through the same configuration.

As far as I can tell, calling `Start()` doesn't throw an exception, exceution continues fine.  I don't notice there's a problem until I try to send a message to the `WhatTimeIsItJob-Q`.

![image](https://cloud.githubusercontent.com/assets/1190907/17043728/788581ee-4f6e-11e6-92d7-00c3cbca3276.png)

**Comment by MarcinHoppe** [comment]
@ppittle I tried to reproduce the issue with SQL Server 2014 Express LocalDb and the callbacks but it worked just fine on my machine and the queue tables were created successfully.

Can you share a debug level log from the startup of the `WhatTimeIsItJob-Q` endpoint when there are no queue tables for this endpoint in the database?

Also, could you post a connection string (of course with all sensitive parameters removed) that you are using?

**Comment by MarcinHoppe** [comment]
Did you manage to have a standalone reproduction of the issue? That would be ideal.

/cc @SeanFeldman

**Comment by ppittle** [comment]
@MarcinHoppe - I was able to isolate the problem.  I'll send you more details tomorrow, but essentially it's a Container issue:

```
var ninjectKernel = new StandardKernel();

var endpoint1 = new EndpointConfiguration();
endpoint1.UseContainer<NinjectBuilder>(c => c.ExistingKernel(ninjectKernel));

var endpoint2 = new EndpointConfiguration();
endpoint2.UseContainer<NinjectBuilder>(c => c.ExistingKernel(new ChildKernel(ninjectKernel));
```

If I start `endpoint1` first and then `endpoint2` it blows up with exceptions listed above.  If I start `endpoint2` first, it's ok.  If I only set a container on one of the endpoints it's ok. 

I originally built the system against the Azure Queue Transport and was finding when I re-use the same Kernel (container) for multiple Endpoints duplicate bindings were added by NServiceBus leading to resolution exceptions.  The [ChildKernel](https://github.com/ninject/ninject.extensions.childkernel) project fixed this by allowing new bindings to be set on the Child Kernel and all other dependencies can be resolved by the parent.  This allows me to only set my bindings in a single place while allowing NSB to set endpoint specific bindings.

**Question:** Is the SqlServer Transport doing anything special with bindings?  I looked through the source and didn't find where the bindings where being set.  My best guess at this point is the binding for `SqlConnectionFactory` is getting mucked up somehow which causes `QueueCreator` to look at the wrong, think the `WhatTimeIsItJob-Q` table has been created already (because it's looking at `SampleJobBank-Q`) and then `ExpiredMessagesPurger` can't `openConnection(queue)` in `Purge`.

**Comment by MarcinHoppe** [comment]
@ppittle Thanks for this additional info. I can observe the same behavior now.

To me, the best solution would be for reach endpoint to have its own child kernel. Your bindings would still be set on the parent kernel. 

I tested such a setup and it worked fine. Is this an option you can consider?

**Comment by MarcinHoppe** [comment]
@ppittle Did you have any chance to try out the child-kernel-per-endpoint approach? Please let me know if I can be of help.

**Comment by ppittle** [comment]
@MarcinHoppe - Sorry.  Yup implemented Child Kernels everywhere and I'm all good.  We can close this up.  Thanks for the help.

**Comment by MarcinHoppe** [comment]
@ppittle No worries. It's great to hear that the solution worked for you!

/cc @SeanFeldman
