### ISSUE TITLE
Outbox dispatches cause queue peek failures

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.SqlServer#310]
## Problem
When SqlServer runs with Outbox from time to time peek operation will fail with message: 

> 2016-10-06 21:58:36.3626|WARN|5|NServiceBus.Transport.SQLServer.QueuePeeker|Sql peek operation failedYou can only specify the READPAST lock in the READ COMMITTED or REPEATABLE READ isolation levels.
>2016-10-06 21:58:36.3716|WARN|5|NServiceBus.Transport.SQLServer.RepeatedFailuresOverTimeCircuitBreaker|The circuit breaker for SqlPeek is now in the armed state

##  Root cause
After investigation it turns out that when doing connection pooling it is possible to have isolation level settings [leaking](http://stackoverflow.com/questions/9851415/sql-server-isolation-level-leaks-across-pooled-connections) between connections in the pool.

What is happening in this case is that pool is shared between:
 * receive operations that set isolation level explicitly to `ReadCommitted`
 * send operations that set isolation level to `Serializable` - Outbox uses DispatchConsistency.Isolated 
 * peek operations that does not set isolation level - this means it will get either `ReadCommitted` or `Serializable` depending who was using the connection last

## Solution 
The solution is to enforce isolation level on the queue peeker.

NOTE: a separate discussion on isolation levels for SqlTransport is required.

<details>
  <summary>Old Content </summary>
  Seems to be unstable in combination with NHibernate Outbox, subscription & saga persistence.

Tested with transaction modes:

- SendsAtomicWIthReceive
 - Results in SQL Peek failure
- ReceiveOnly
 - Sequential processing (concurrency=1) does not result in a failing SQL Peek. Concurrency>1 does result in errors.
- TransactionScope 
 - Hangs the message processing. Tried various concurrency levels but sequential processing doesn't work either.

```
2016-10-06 21:58:36.3626|WARN|5|NServiceBus.Transport.SQLServer.QueuePeeker|Sql peek operation failedYou can only specify the READPAST lock in the READ COMMITTED or REPEATABLE READ isolation levels.
2016-10-06 21:58:36.3716|WARN|5|NServiceBus.Transport.SQLServer.RepeatedFailuresOverTimeCircuitBreaker|The circuit breaker for SqlPeek is now in the armed state
```
</details>

**Comment by ramonsmits** [comment]
Additional info:

- Specifying `Pooling=False` makes it work for core V5 and V6 
- TransactionScope works for core V5
- TransactionScope fails for core V6 because it wants to promote

```
NHibernate.TransactionException: Begin failed with SQL exception ---> System.Data.SqlClient.SqlException: MSDTC on server 'ZOLDER\SQLEXPRESS' is unavailable.
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at NHibernate.Connection.DriverConnectionProvider.GetConnection()
   at NHibernate.AdoNet.ConnectionManager.GetConnection()
   at NHibernate.Transaction.AdoTransaction.Begin(IsolationLevel isolationLevel)
   --- End of inner exception stack trace ---
   at NHibernate.Transaction.AdoTransaction.Begin(IsolationLevel isolationLevel)
   at NHibernate.Impl.SessionImpl.BeginTransaction()
   at NServiceBus.Persistence.NHibernate.OutboxPersister.BeginTransaction(ContextBag context)
   at NServiceBus.TransportReceiveToPhysicalMessageProcessingConnector.<Invoke>d__1.MoveNext() in C:\Build\src\NServiceBus.Core\Pipeline\Incoming\TransportReceiveToPhysicalMessageProcessingConnector.cs:line 34
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Performance.StatisticsBehavior.<Invoke>d__2.MoveNext() in C:\Users\ramon\src\particular\EndToEnd\src\PerformanceTests\Common\Statistics\StatisticsBehavior.V6.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.MainPipelineExecutor.<Invoke>d__1.MoveNext() in C:\Build\src\NServiceBus.Core\Pipeline\MainPipelineExecutor.cs:line 32
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.SQLServer.ReceiveStrategy.<TryProcessingMessage>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.SQLServer.ReceiveWithTransactionScope.<TryProcess>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.SQLServer.ReceiveWithTransactionScope.<ReceiveMessage>d__1.MoveNext()
```

**Comment by ramonsmits** [comment]
After research with @tmasternak we found that the connection pool connections are returned with different transaction isolation levels. This is due to the DispatchAsIsolated not explicitly setting a transaction isolation level and the peek not using a transaction scope at all.

Creating a transaction scope using isolation level ReadCommitted for the peek resolves the issue.

**Comment by tmasternak** [comment]
Closing this one #311 went in and I've created discussion about isolation level support.
