### ISSUE TITLE
Constantly getting transaction/connection exceptions

### ISSUE THREAD

**Issue by dasjestyr** [Particular/NServiceBus.SqlServer#359]
So I have a process that issues a few thousand commands to the bus and I'm not getting errors during that part. While I'm waiting for the handler for that command to pick up and hit a break point (which it never does), NSB is emitting and exception that indicates that a connection has not been disposed and/or it's causing some conflict with the transaction. A couple other things I noticed is that, while a few thousand command were issued, the table/queue only contains one or two. And this happens maybe 90% of the time. There were a couple times where things appeared to be behaving properly and then, without any changes, it would break on subsequent runs. Here is the exception

```
System.Exception: Failed to send message to [dbo].[DAS.Services.Reviews] ---> System.InvalidOperationException: The transaction associated with the current connection has completed but has not been disposed.  The transaction must be disposed before the connection can be used to execute SQL statements.
   at System.Data.SqlClient.TdsParser.TdsExecuteRPC(SqlCommand cmd, _SqlRPC[] rpcArray, Int32 timeout, Boolean inSchema, SqlNotificationRequest notificationRequest, TdsParserStateObject stateObj, Boolean isCommandProc, Boolean sync, TaskCompletionSource`1 completion, Int32 startRpc, Int32 startParam)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.BeginExecuteNonQueryInternal(CommandBehavior behavior, AsyncCallback callback, Object stateObject, Int32 timeout, Boolean inRetry, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.BeginExecuteNonQueryAsync(AsyncCallback callback, Object stateObject)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl(Func`3 beginMethod, Func`2 endFunction, Action`1 endAction, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory`1.FromAsync(Func`3 beginMethod, Func`2 endMethod, Object state)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQueryAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.SQLServer.TableBasedQueue.<SendRawMessage>d__9.MoveNext() in C:\BuildAgent\work\888dd942b44bad5a\src\NServiceBus.SqlServer\Queuing\TableBasedQueue.cs:line 91
   --- End of inner exception stack trace ---
   at NServiceBus.Transport.SQLServer.TableBasedQueue.ThrowFailedToSendException(Exception ex) in C:\BuildAgent\work\888dd942b44bad5a\src\NServiceBus.SqlServer\Queuing\TableBasedQueue.cs:line 128
   at NServiceBus.Transport.SQLServer.TableBasedQueue.<SendRawMessage>d__9.MoveNext() in C:\BuildAgent\work\888dd942b44bad5a\src\NServiceBus.SqlServer\Queuing\TableBasedQueue.cs:line 103
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.SQLServer.TableBasedQueueDispatcher.<Send>d__6.MoveNext() in C:\BuildAgent\work\888dd942b44bad5a\src\NServiceBus.SqlServer\Sending\TableBasedQueueDispatcher.cs:line 96
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.SQLServer.TableBasedQueueDispatcher.<DispatchAsIsolated>d__2.MoveNext() in C:\BuildAgent\work\888dd942b44bad5a\src\NServiceBus.SqlServer\Sending\TableBasedQueueDispatcher.cs:line 27
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.SQLServer.MessageDispatcher.<Dispatch>d__1.MoveNext() in C:\BuildAgent\work\888dd942b44bad5a\src\NServiceBus.SqlServer\Sending\MessageDispatcher.cs:line 20
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.TransportReceiveToPhysicalMessageProcessingConnector.<Invoke>d__1.MoveNext() in C:\Build\src\NServiceBus.Core\Pipeline\Incoming\TransportReceiveToPhysicalMessageProcessingConnector.cs:line 57
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.MainPipelineExecutor.<Invoke>d__1.MoveNext() in C:\Build\src\NServiceBus.Core\Pipeline\MainPipelineExecutor.cs:line 32
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.SQLServer.ReceiveStrategy.<TryProcessingMessage>d__12.MoveNext() in C:\BuildAgent\work\888dd942b44bad5a\src\NServiceBus.SqlServer\Receiving\ReceiveStrategy.cs:line 33
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.SQLServer.ReceiveWithNativeTransaction.<TryProcess>d__4.MoveNext() in C:\BuildAgent\work\888dd942b44bad5a\src\NServiceBus.SqlServer\Receiving\ReceiveWithNativeTransaction.cs:line 112

```

**Comment by SzymonPobiega** [comment]
Hi Jeremy

Can you post the piece of code that issues the commands?

Szymon

2017-04-10 20:43 GMT+02:00 Jeremy Stafford <notifications@github.com>:

**Comment by dasjestyr** [comment]
``` csharp
private async Task SendIngestionCommand(
  Guid clientId,
  IMessageHandlerContext context,
  ReviewSource source,
  List<string> clientSiteIds)
{
  foreach (var siteId in clientSiteIds)
  {
      var command = new BulkIngestionCommand
      {
          ClientId = clientId,
          ReviewSource = source.ToString(),
          ExternalClientId = siteId,
          RequestDateTime = DateTime.Now
      };
      
      if(_shouldSpawnCommands)
      { 
          await context.SendLocal(command).ConfigureAwait(false);
          Logger.Verbose("Queued ingestion command for client {@Command}.", this, command);
      }
  }
}
```

**Comment by SzymonPobiega** [comment]
Hi Jeremy

Can you also post the configuration code of your endpoint?

Szymon

2017-04-12 18:25 GMT+02:00 Jeremy Stafford <notifications@github.com>:

**Comment by SzymonPobiega** [comment]
I've tried reproducing this behavior but failed. [Here](https://gist.github.com/SzymonPobiega/20ad01f120e3a9d57f109c9af51d0944) is a gist containing my repro. Can you take a look and verify that is is equivalent to your code? 

The fact that you only see two messages in the queue but the logger logs all of them is because, by default, the sending of the messages is delayed. The `SendLocal` call only appends the outgoing message to a collection and all messages are dispatched after the handler code finishes execution.

In case of Outbox (and it seems you have it enabled), all the messages are stored in an outbox record and then dispatched, one by one. If the dispatch process fails, the message is retried but this time the handler is not invoked. Only the stored messages are dispatched.

**Comment by dasjestyr** [comment]
My config has changed and I can no longer troubleshoot this. I had to move on and get something pushed so I ended up just switching the transport to Azure Service Bus which I think was probably a better move anyway. Thanks for the help.

**Comment by SzymonPobiega** [comment]
@dasjestyr if you are on azure that indeed might be a good move from the cost perspective (ASB and ASQ are much cheaper to run given same volume of messages). The difference between ASB and SQL transports lies in the way the handlers should access their data. Since ASB does not allow the transaction to include data access make sure that the handler logic is either idempotent by nature or you enabled Outbox.
