### ISSUE TITLE
Dotnet Core with default transaction mode MessagePump|Sql receive operation failed : NotSupportedException: Enlisting in Ambient transactions is not supported.

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.SqlServer#417]
Running on dotnet core without selecting a transaction mode results in the following error:

```
2017-11-21 10:49:07,910|WARN|20|NServiceBus.Transport.SQLServer.MessagePump|Sql receive operation failed
System.NotSupportedException: Enlisting in Ambient transactions is not supported.
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.OpenAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.SQLServer.SqlConnectionFactory.<>c__DisplayClass2_0.<<Default>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.SQLServer.SqlConnectionFactory.<OpenNewConnection>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.SQLServer.ProcessWithTransactionScope.<ReceiveMessage>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.SQLServer.MessagePump.<InnerReceive>d__6.MoveNext()
```

**Comment by SzymonPobiega** [comment]
This is fine. Microsoft "promised" to deliver support for `TransactionScope` in 2.1 of .net core. Until this happens, users are doomed to native transaction mode. If we added handling of this case they we would need to release a new version when MS releases core 2.1

**Comment by ramonsmits** [comment]
If this is as expected we should at least document this.

**Comment by SzymonPobiega** [comment]
https://docs.particular.net/transports/sql/transactions?version=sqltransport_4#transaction-scope-distributed-transaction

**Comment by ramonsmits** [comment]
I've created a PR to improve the doco which is enough to close this.
