### ISSUE TITLE
any plans to move to Microsoft.Data.SqlClient ?

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus.SqlServer#503]
https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/

**Comment by DavidBoike** [comment]
Hey @SimonCropp. Not immediately. You're the first to ask, and of course it's only been out of preview for a couple weeks.

I imagine we'd have to release new concurrent majors of SQL Transport and Persistence, so it would be a bit of an undertaking.

**Comment by SimonCropp** [comment]
I assume sharing the connection and transaction will still be a supported scenario in EF 3? https://docs.particular.net/samples/sqltransport-sqlpersistence/#receiver-project-accessing-the-ambient-database-details-entityframework-persisting-data

If so then the work will have to be done since Microsoft.EntityFrameworkCore.SqlServer is moving to Microsoft.Data.SqlClient https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.SqlServer/3.0.0-rc1.19456.14

**Comment by SimonCropp** [comment]
any response to the above ?

**Comment by DavidBoike** [comment]
@SimonCropp I assume the connection and transaction sharing would need to remain a supported scenario, which you are correct would block people from updating to EFCore3. But the fact that it is blocking in some way will contribute to a higher priority. But I don't think that blocking EFCore3 qualifies it for immediate prioritization.

**Comment by SimonCropp** [comment]
i wasnt expecting "immediate prioritization". but i was expecting some level of movement given the announcement, the beta package, and the beta of EF using it, were all released 5 month ago. also a go live license was issued for these packages a month ago.

**Comment by SimonCropp** [comment]
i give in.

**Comment by DavidBoike** [comment]
Replaced by https://github.com/Particular/NServiceBus.SqlServer/issues/506

**Comment by robbaman** [comment]
> I assume sharing the connection and transaction will still be a supported scenario in EF 3? https://docs.particular.net/samples/sqltransport-sqlpersistence/#receiver-project-accessing-the-ambient-database-details-entityframework-persisting-data
> 
> If so then the work will have to be done since Microsoft.EntityFrameworkCore.SqlServer is moving to Microsoft.Data.SqlClient https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.SqlServer/3.0.0-rc1.19456.14

It looks like this doesn't work anymore. We're getting issues when sharing the DbTransaction between NServiceBus and EFCore 3.0 because of the exception:

```
NServiceBus.RecoverabilityExecutor - Moving message 'e9bdb375-d0b0-4010-917e-ab3600b2fec3' to the error queue 'error' because processing failed due to an exception:
System.InvalidCastException: Unable to cast object of type 'Microsoft.Data.SqlClient.SqlParameter' to type 'System.Data.SqlClient.SqlParameter'.
   at NServiceBus.SqlDialect.MsSqlServer.SetParameterValue(DbParameter parameter, Object value)
   at NServiceBus.SqlDialect.MsSqlServer.SetJsonParameterValue(DbParameter parameter, Object value)
   at NServiceBus.SqlDialect.AddJsonParameter(DbParameter parameter, String paramName, Object value)
   at CommandWrapper.AddJsonParameter(String name, Object value)
   at SagaPersister.Save(IContainSagaData sagaData, SynchronizedStorageSession session, Object correlationId)
   at NServiceBus.SagaPersistenceBehavior.Invoke(IInvokeHandlerContext context, Func`2 next)
   at NServiceBus.LoadHandlersConnector.Invoke(IIncomingLogicalMessageContext context, Func`2 stage)
   at NServiceBus.ScheduledTaskHandlingBehavior.Invoke(IIncomingLogicalMessageContext context, Func`2 next)
   at NServiceBus.InvokeSagaNotFoundBehavior.Invoke(IIncomingLogicalMessageContext context, Func`2 next)
   at NServiceBus.DeserializeMessageConnector.Invoke(IIncomingPhysicalMessageContext context, Func`2 stage)
   at ReceivePerformanceDiagnosticsBehavior.Invoke(IIncomingPhysicalMessageContext context, Func`2 next)
   at NServiceBus.InvokeAuditPipelineBehavior.Invoke(IIncomingPhysicalMessageContext context, Func`2 next)
   at NServiceBus.ProcessingStatisticsBehavior.Invoke(IIncomingPhysicalMessageContext context, Func`2 next)
   at NServiceBus.TransportReceiveToPhysicalMessageConnector.Invoke(ITransportReceiveContext context, Func`2 next)
   at NServiceBus.MainPipelineExecutor.Invoke(MessageContext messageContext)
   at NServiceBus.Transport.RabbitMQ.MessagePump.Process(BasicDeliverEventArgs message)
```

We thought we had solved the issue by explicitly using the new SqlConnection when configuring the endpoint:

```
persistence.ConnectionBuilder(() => new Microsoft.Data.SqlClient.SqlConnection(options.DatabaseConnectionString));
```

But this just moved the error from EF Core Queries to NServiceBus Queries...
