### ISSUE TITLE
With 2.1.1 Host crashes when using StructureMap

### ISSUE THREAD

**Issue by pedroreys** [Particular/NServiceBus.SqlServer#76]
### Symptoms

Endpoint either fails to start (StructureMap) or fails when trying to process a message (Autofac), depending on how "smart" container is with regards to discovering incomplete registrations.

### Who's affected

All who use SQL Server transport with StructureMap. For other containers only users who wish to access the underlying transport connection or transaction using `SqlServerStorageContext` class.

### Root cause

The `SqlServerStorageContext` has wrong container registration code.

### Original issue

With NServiceBus.SqlServer 2.0.2 this configuration works just fine. Updating it to 2.1.1 causes the Host to crash when starting up.

Here is my Endpoint Config:

````csharp
public class EndpointConfig : IConfigureThisEndpoint, AsA_Server
{
    public void Customize(BusConfiguration configuration)
    {
        var container = IoC.Container;

        configuration.UseContainer<StructureMapBuilder>(c => c.ExistingContainer(container));

        var dbConfig = container.GetInstance<DbAppConfig>();

       configuration.EndpointName("MyEndpoint");

        configuration
            .UseTransport<SqlServerTransport>()
            .ConnectionString(dbConfig.ConnectionString);

        configuration
            .UsePersistence<NHibernatePersistence>()
            .ConnectionString(dbConfig.ConnectionString);
    }
}
````

And here is the exception that is thrown:

````
System.ArgumentOutOfRangeException was unhandled by user code
  HResult=-2146233086
  Message=Specified argument was out of the range of valid values.
Parameter name: NServiceBus.Transports.SQLServer.SqlServerStorageContext must have at least one public constructor to be plugged in by StructureMap
  Source=StructureMap
  ParamName=NServiceBus.Transports.SQLServer.SqlServerStorageContext must have at least one public constructor to be plugged in by StructureMap
  StackTrace:
       at StructureMap.Pipeline.ConstructorInstance`1..ctor(Type concreteType) in c:\BuildAgent\work\996e173a8ceccdca\src\StructureMap\Pipeline\ConstructorInstance.cs:line 49
       at StructureMap.Pipeline.ConfiguredInstance..ctor(Type pluggedType) in c:\BuildAgent\work\996e173a8ceccdca\src\StructureMap\Pipeline\ConfiguredInstance.cs:line 21
       at StructureMap.Configuration.DSL.Expressions.GenericFamilyExpression.Use(Type concreteType) in c:\BuildAgent\work\996e173a8ceccdca\src\StructureMap\Configuration\DSL\Expressions\GenericFamilyExpression.cs:line 63
       at StructureMapObjectBuilder.<>c__DisplayClass7.<Configure>b__6(ConfigurationExpression x) in c:\BuildAgent\work\a747c5035db63b72\src\NServiceBus.StructureMap\StructureMapObjectBuilder.cs:line 91
       at StructureMap.PipelineGraph.Configure(Action`1 configure) in c:\BuildAgent\work\996e173a8ceccdca\src\StructureMap\PipelineGraph.cs:line 148
       at StructureMap.Container.Configure(Action`1 configure) in c:\BuildAgent\work\996e173a8ceccdca\src\StructureMap\Container.cs:line 390
       at StructureMapObjectBuilder.Configure(Type component, DependencyLifecycle dependencyLifecycle) in c:\BuildAgent\work\a747c5035db63b72\src\NServiceBus.StructureMap\StructureMapObjectBuilder.cs:line 89
       at NServiceBus.ObjectBuilder.Common.CommonObjectBuilder.ConfigureComponent[T](DependencyLifecycle instanceLifecycle) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\ObjectBuilder\Common\CommonObjectBuilder.cs:line 45
       at NServiceBus.Features.SqlServerTransportFeature.Configure(FeatureConfigurationContext context, String connectionStringWithSchema) in c:\BuildAgent\work\888dd942b44bad5a\src\NServiceBus.SqlServer\Config\SqlServerTransportFeature.cs:line 67
       at NServiceBus.Transports.ConfigureTransport.Setup(FeatureConfigurationContext context) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Transports\ConfigureTransport.cs:line 48
       at NServiceBus.Features.Feature.SetupFeature(FeatureConfigurationContext config) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Features\Feature.cs:line 203
       at NServiceBus.Features.FeatureActivator.ActivateFeature(FeatureState featureState, IEnumerable`1 featuresToActivate, FeatureConfigurationContext context) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Features\FeatureActivator.cs:line 233
       at NServiceBus.Features.FeatureActivator.SetupFeatures(FeatureConfigurationContext context) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Features\FeatureActivator.cs:line 118
       at NServiceBus.Configure.Initialize() in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Configure.cs:line 115
       at NServiceBus.Bus.Create(BusConfiguration configuration) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Bus.cs:line 21
       at NServiceBus.GenericHost.PerformConfiguration(Action`1 moreConfiguration) in c:\BuildAgent\work\a3de8759ee491634\src\NServiceBus.Hosting.Windows\GenericHost.cs:line 121
       at NServiceBus.GenericHost.Start() in c:\BuildAgent\work\a3de8759ee491634\src\NServiceBus.Hosting.Windows\GenericHost.cs:line 70
       at NServiceBus.Hosting.Windows.WindowsHost.Start() in c:\BuildAgent\work\a3de8759ee491634\src\NServiceBus.Hosting.Windows\WindowsHost.cs:line 30
       at NServiceBus.Hosting.Windows.Program.<>c__DisplayClasse.<Main>b__6(WindowsHost service) in c:\BuildAgent\work\a3de8759ee491634\src\NServiceBus.Hosting.Windows\Program.cs:line 80
       at Topshelf.Internal.ControllerDelegates`1.StartActionObject(Object obj) in c:\Projects\TopShelfForNSB\src\Topshelf\Internal\ControllerDelegates.cs:line 18
       at Topshelf.Internal.IsolatedServiceControllerWrapper`1.<>c__DisplayClass2.<set_StartAction>b__1(TService service) in c:\Projects\TopShelfForNSB\src\Topshelf\Internal\IsolatedServiceControllerWrapper.cs:line 65
       at Topshelf.Internal.ServiceController`1.<.cctor>b__1(ServiceController`1 sc) in c:\Projects\TopShelfForNSB\src\Topshelf\Internal\ServiceController.cs:line 35
       at Magnum.StateMachine.LambdaAction`1.Execute(T instance, Event event, Object parameter) in :line 0
       at Magnum.StateMachine.EventActionList`1.Execute(T stateMachine, Event event, Object parameter) in :line 0
  InnerException: 

````

**Comment by SzymonPobiega** [comment]
@pedroreys thank you for a detailed report. We're working on the fix.

**Comment by pedroreys** [comment]
thanks for the quick response @SzymonPobiega!
