### ISSUE TITLE
System.NullReferenceException was unhandled by user code

### ISSUE THREAD

**Issue by johnsimons** [Particular/NServiceBus.SqlServer#79]
### Symptoms

A `NullReferenceException` is throws when shutting down the endpoint

### Who's affected

All users of 2.1.0, 2.1.1 and 2.1.2

### Root cause

There is a race condition in the shut down code

```
System.NullReferenceException was unhandled by user code
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=NServiceBus.Transports.SQLServer
  StackTrace:
       at NServiceBus.Transports.SQLServer.AdaptiveExecutor`1.<>c__DisplayClass3.<StartTask>b__1(Task t) in c:\BuildAgent\work\888dd942b44bad5a\src\NServiceBus.SqlServer\AdaptiveExecutor.cs:line 59
       at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
       at System.Threading.Tasks.Task.Execute()
  InnerException: 
```

**Comment by johnsimons** [comment]
@SzymonPobiega added a fix for this, can u review it ?

**Comment by SzymonPobiega** [comment]
Looks good @johnsimons . Thanks.

**Comment by rlaveycal** [comment]
Is this going to be released soon? It's really annoying.

**Comment by johnsimons** [comment]
@SzymonPobiega we should release this ?
