### ISSUE TITLE
Sql2012 acceptance tests fails with The transport is running in native SQL Server transactions mode without an outbox, but configuration uses multi-database sending

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus.SqlServer#89]
http://builds.particular.net/viewLog.html?buildId=119082&buildTypeId=NServiceBusSqlServer_2RunAcceptanceTests

```
Exceptions = System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.Exception: The transport is running in native SQL Server transactions mode without an outbox, but configuration uses multi-database sending (http://docs.particular.net/nservicebus/sqlserver/multiple-databases). Multi-database sends can only be used when either in ambient transaction mode or when outbox is enabled. Please check your endpoint configuration.
   at NServiceBus.Features.ValidateOutboxOrAmbientTransactionsEnabled.ValiateTask.OnStart() in c:\BuildAgent\work\888dd942b44bad5a\src\NServiceBus.SqlServer\Config\ValidateOutboxOrAmbientTransactionsEnabled.cs:line 36
   at NServiceBus.Features.FeatureActivator.StartFeatures(IBuilder builder) in c:\BuildAgent\work\1b05a2fea6e4cd32\src\NServiceBus.Core\Features\FeatureActivator.cs:line 135
   at NServiceBus.Unicast.UnicastBus.<

```

**Comment by SzymonPobiega** [comment]
These `When_in_native_transaction_mode` all all flaky. I suppose that is because they are based on exception text and that was not super-reliable back in remoting days. I hope that with V6 and getting rid of remoting in the acceptance tests we'll be able to stabilize it. Currently thinking about muting them...

**Comment by MarcinHoppe** [comment]
@SzymonPobiega @andreasohlund This is oldie. Can we close?

**Comment by andreasohlund** [comment]
fine by me
