### ISSUE TITLE
V2: Potential missing Dispose call

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus.SqlServer#97]
### Who's affected

Everybody

### Symptoms

```
Failed to send message to address: AgWorks.ServiceBus.Local001.audit@KANPAL-NEW<mailto:AgWorks.ServiceBus.Local001.audit@KANPAL-NEW>
System.Exception: Failed to send message to address: AgWorks.ServiceBus.Local001.audit@KANPAL-NEW ---> System.InvalidOperationException: The transaction associated with the current connection has completed but has not been disposed. The transaction must be disposed before the connection can be used to execute SQL statements.
at System.Data.SqlClient.TdsParser.TdsExecuteRPC(SqlCommand cmd, _SqlRPC[] rpcArray, Int32 timeout, Boolean inSchema, SqlNotificationRequest notificationRequest, TdsParserStateObject stateObj, Boolean isCommandProc, Boolean sync, TaskCompletionSource`1 completion, Int32 startRpc, Int32 startParam)
at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
at NServiceBus.Transports.SQLServer.TableBasedQueue.ExecuteSendQuery(Object[] messageData, SqlCommand command) in C:\BuildAgent\work\888dd942b44bad5a\src\NServiceBus.SqlServer\TableBasedQueue.cs:line 53
at NServiceBus.Transports.SQLServer.TableBasedQueue.Send(Object[] messageData, SqlConnection connection, SqlTransaction transaction) in C:\BuildAgent\work\888dd942b44bad5a\src\NServiceBus.SqlServer\TableBasedQueue.cs:line 43
at NServiceBus.Transports.SQLServer.TableBasedQueue.Send(TransportMessage message, SendOptions sendOptions, SqlConnection connection, SqlTransaction transaction) in C:\BuildAgent\work\888dd942b44bad5a\src\NServiceBus.SqlServer\TableBasedQueue.cs:line 29
at NServiceBus.Transports.SQLServer.SqlServerMessageSender.Send(TransportMessage message, SendOptions sendOptions) in C:\BuildAgent\work\888dd942b44bad5a\src\NServiceBus.SqlServer\SqlServerMessageSender.cs:line 46
--- End of inner exception stack trace ---
at NServiceBus.Transports.SQLServer.SqlServerMessageSender.ThrowFailedToSendException(Address address, Exception ex) in C:\BuildAgent\work\888dd942b44bad5a\src\NServiceBus.SqlServer\SqlServerMessageSender.cs:line 128
at NServiceBus.Transports.SQLServer.SqlServerMessageSender.Send(TransportMessage message, SendOptions sendOptions) in C:\BuildAgent\work\888dd942b44bad5a\src\NServiceBus.SqlServer\SqlServerMessageSender.cs:line 82
at NServiceBus.Transports.DefaultMessageAuditer.Audit(SendOptions sendOptions, TransportMessage transportMessage) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Audit\DefaultMessageAuditer.cs:line 59
at CallSite.Target(Closure , CallSite , Object , SendOptions , TransportMessage )
at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
at NServiceBus.Transports.AuditerWrapper.Audit(SendOptions sendOptions, TransportMessage message) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Audit\DefaultMessageAuditer.cs:line 22
at NServiceBus.AuditBehavior.Invoke(IncomingContext context, Action next) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Audit\AuditBehavior.cs:line 32
at NServiceBus.BehaviorChain`1.InvokeNext(T context) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\BehaviorChain.cs:line 107
at NServiceBus.BehaviorChain`1.Invoke() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\BehaviorChain.cs:line 52
at NServiceBus.Pipeline.PipelineExecutor.Execute[T](BehaviorChain`1 pipelineAction, T context) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\PipelineExecutor.cs:line 130
at NServiceBus.Pipeline.PipelineExecutor.InvokePipeline[TContext](IEnumerable`1 behaviors, TContext context) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\PipelineExecutor.cs:line 86
at NServiceBus.Pipeline.PipelineExecutor.InvokeReceivePhysicalMessagePipeline() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\PipelineExecutor.cs:line 103
at NServiceBus.Unicast.UnicastBus.TransportMessageReceived(Object sender, TransportMessageReceivedEventArgs e) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\UnicastBus.cs:line 827
at NServiceBus.Unicast.Transport.TransportReceiver.OnTransportMessageReceived(TransportMessage msg) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\Transport\TransportReceiver.cs:line 413
at NServiceBus.Unicast.Transport.TransportReceiver.ProcessMessage(TransportMessage message) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\Transport\TransportReceiver.cs:line 346
at NServiceBus.Unicast.Transport.TransportReceiver.TryProcess(TransportMessage message) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\Transport\TransportReceiver.cs:line 230
at NServiceBus.Transports.SQLServer.AmbientTransactionReceiveStrategy.TryReceiveFrom(TableBasedQueue queue) in C:\BuildAgent\work\888dd942b44bad5a\src\NServiceBus.SqlServer\AmbientTransactionReceiveStrategy.cs:line 57
```

**Comment by SzymonPobiega** [comment]
This exception actually is caused by a transaction timeout when using `TransactionScope`. Usually means the handler executes longer than 1 minute (default value) or 10 minutes (maximum value set in `machine.config`)

**Comment by SzymonPobiega** [comment]
There is nothing we can do about this on our side.
